name: Auto-Tag Release
on:
  push:
    branches: [main]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Klemensas/action-autotag@v1.0.0  # Use stable v1.0.0
        with:
          package_root: "."  # Root directory where pyproject.toml/setup.py lives
