name: Auto-Tag Release
on:
  push:
    branches: [main]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Required here
          custom_tag: "v${{ github.ref_version }}"  # Optional: formats tag as v1.0.0
