name: Auto-Tag Release
on:
  push:
    branches: [main]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.1  # Works with any version file
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
